name: CI

on:
  push:
  pull_request:
  schedule:
    # midnight UTC on the 1st of every month.
    - cron: '0 0 1 * *'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: vet
        run: go vet ./...

      - name: fmt
        run: gofmt -w -s . && git diff --exit-code

      - name: fix
        run: go fix ./... && git diff --exit-code

      - name: test
        run: go test ./...
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
